# Generated by Django 5.1.4 on 2024-12-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_pushed',
            new_name='is_read',
        ),
    ]
